## annual_supply_raw.csv

In [2]:
import pandas as pd

pd.set_option("display.max_columns", None)

path = "data/raw/nass/annual_supply_raw.csv"
df = pd.read_csv(path, low_memory=False)

In [3]:
df.info()
print("Shape:", df.shape)
display(df.head(),)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15224 entries, 0 to 15223
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   source_desc            15224 non-null  object
 1   sector_desc            15224 non-null  object
 2   group_desc             15224 non-null  object
 3   commodity_desc         15224 non-null  object
 4   class_desc             15224 non-null  object
 5   prodn_practice_desc    15224 non-null  object
 6   util_practice_desc     15224 non-null  object
 7   statisticcat_desc      15224 non-null  object
 8   unit_desc              15224 non-null  object
 9   short_desc             15224 non-null  object
 10  domain_desc            15224 non-null  object
 11  domaincat_desc         15224 non-null  object
 12  agg_level_desc         15224 non-null  object
 13  state_ansi             14519 non-null  float64
 14  state_fips_code        15224 non-null  int64
 15  state_alpha            15224 non-null  object
 16  state_name             15224 non-null  object
 17  asd_code               0 non-null      float64
 18  asd_desc               0 non-null      float64
 19  county_ansi            0 non-null      float64
 20  county_code            0 non-null      float64
 21  county_name            0 non-null      float64
 22  region_desc            0 non-null      float64
 23  zip_5                  0 non-null      float64
 24  watershed_code         15224 non-null  int64
 25  watershed_desc         0 non-null      float64
 26  congr_district_code    0 non-null      float64
 27  country_code           15224 non-null  int64
 28  country_name           15224 non-null  object
 29  location_desc          15224 non-null  object
 30  year                   15224 non-null  int64
 31  freq_desc              15224 non-null  object
 32  begin_code             15224 non-null  int64
 33  end_code               15224 non-null  int64
 34  reference_period_desc  15224 non-null  object
 35  week_ending            0 non-null      float64
 36  load_time              15224 non-null  object
 37  Value                  15224 non-null  object
 38  CV (%)                 0 non-null      float64
dtypes: float64(12), int64(6), object(21)
memory usage: 4.5+ MB
Shape: (15224, 39)

,source_desc,sector_desc,group_desc,commodity_desc,class_desc,prodn_practice_desc,util_practice_desc,statisticcat_desc,unit_desc,short_desc,domain_desc,domaincat_desc,agg_level_desc,state_ansi,state_fips_code,state_alpha,state_name,asd_code,asd_desc,county_ansi,county_code,county_name,region_desc,zip_5,watershed_code,watershed_desc,congr_district_code,country_code,country_name,location_desc,year,freq_desc,begin_code,end_code,reference_period_desc,week_ending,load_time,Value,CV (%)
0,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,AREA PLANTED,ACRES,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2026,ANNUAL,0,0,YEAR,NaN,2026-03-31 12:00:00.000,"95,338,000",NaN
1,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,AREA PLANTED,ACRES,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2026,ANNUAL,0,0,YEAR - MAR ACREAGE,NaN,2026-03-31 12:00:00.000,"95,338,000",NaN
2,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,AREA PLANTED,ACRES,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,ANNUAL,0,0,YEAR,NaN,2026-01-12 12:00:00.000,"98,788,000",NaN
3,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,AREA PLANTED,ACRES,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,ANNUAL,0,0,YEAR - AUG FORECAST,NaN,2025-08-12 12:00:00.000,"97,254,000",NaN
4,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,AREA PLANTED,ACRES,CORN - ACRES PLANTED,TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,ANNUAL,0,0,YEAR - JUN ACREAGE,NaN,2025-06-30 12:00:00.000,"95,203,000",NaN

In [4]:
df["Value_num"] = (
    df["Value"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace(r"[^0-9.\-]", "", regex=True)
)
df["Value_num"] = pd.to_numeric(df["Value_num"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15224 entries, 0 to 15223
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   source_desc            15224 non-null  object
 1   sector_desc            15224 non-null  object
 2   group_desc             15224 non-null  object
 3   commodity_desc         15224 non-null  object
 4   class_desc             15224 non-null  object
 5   prodn_practice_desc    15224 non-null  object
 6   util_practice_desc     15224 non-null  object
 7   statisticcat_desc      15224 non-null  object
 8   unit_desc              15224 non-null  object
 9   short_desc             15224 non-null  object
 10  domain_desc            15224 non-null  object
 11  domaincat_desc         15224 non-null  object
 12  agg_level_desc         15224 non-null  object
 13  state_ansi             14519 non-null  float64
 14  state_fips_code        15224 non-null  int64
 15  state_alpha            15224 non-null  object
 16  state_name             15224 non-null  object
 17  asd_code               0 non-null      float64
 18  asd_desc               0 non-null      float64
 19  county_ansi            0 non-null      float64
 20  county_code            0 non-null      float64
 21  county_name            0 non-null      float64
 22  region_desc            0 non-null      float64
 23  zip_5                  0 non-null      float64
 24  watershed_code         15224 non-null  int64
 25  watershed_desc         0 non-null      float64
 26  congr_district_code    0 non-null      float64
 27  country_code           15224 non-null  int64
 28  country_name           15224 non-null  object
 29  location_desc          15224 non-null  object
 30  year                   15224 non-null  int64
 31  freq_desc              15224 non-null  object
 32  begin_code             15224 non-null  int64
 33  end_code               15224 non-null  int64
 34  reference_period_desc  15224 non-null  object
 35  week_ending            0 non-null      float64
 36  load_time              15224 non-null  object
 37  Value                  15224 non-null  object
 38  CV (%)                 0 non-null      float64
 39  Value_num              15224 non-null  float64
dtypes: float64(13), int64(6), object(21)
memory usage: 4.6+ MB

In [5]:
pd.set_option("display.max_colwidth", None)

In [6]:
# 1. 每一列的类型、缺失率、唯一值数量、样例

profile = []

for col in df.columns:
    s = df[col]
    row = {
        "column": col,
        "dtype": str(s.dtype),
        "non_null": int(s.notna().sum()),
        "missing_pct": round(s.isna().mean() * 100, 2),
        "n_unique": int(s.nunique(dropna=True)),
        "sample_values": s.dropna().astype(str).unique()[:8].tolist(),
    }

    if pd.api.types.is_numeric_dtype(s):
        row.update({
            "min": s.min(),
            "median": s.median(),
            "max": s.max(),
        })
    else:
        row.update({
            "min": None,
            "median": None,
            "max": None,
        })

    profile.append(row)


profile_df = pd.DataFrame(profile)
display(profile_df)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

,column,dtype,non_null,missing_pct,n_unique,sample_values,min,median,max
0,source_desc,object,15224,0.00,1,[SURVEY],NaN,NaN,NaN
1,sector_desc,object,15224,0.00,1,[CROPS],NaN,NaN,NaN
2,group_desc,object,15224,0.00,1,[FIELD CROPS],NaN,NaN,NaN
3,commodity_desc,object,15224,0.00,2,"[CORN, SOYBEANS]",NaN,NaN,NaN
4,class_desc,object,15224,0.00,1,[ALL CLASSES],NaN,NaN,NaN
5,prodn_practice_desc,object,15224,0.00,1,[ALL PRODUCTION PRACTICES],NaN,NaN,NaN
6,util_practice_desc,object,15224,0.00,2,"[ALL UTILIZATION PRACTICES, GRAIN]",NaN,NaN,NaN
7,statisticcat_desc,object,15224,0.00,4,"[AREA PLANTED, AREA HARVESTED, YIELD, PRODUCTION]",NaN,NaN,NaN
8,unit_desc,object,15224,0.00,3,"[ACRES, BU / ACRE, BU]",NaN,NaN,NaN
9,short_desc,object,15224,0.00,8,"[CORN - ACRES PLANTED, CORN, GRAIN - ACRES HARVESTED, CORN, GRAIN - YIELD, MEASURED IN BU / ACRE, CORN, GRAIN - PRODUCTION, MEASURED IN BU, SOYBEANS - ACRES PLANTED, SOYBEANS - ACRES HARVESTED, SOYBEANS - YIELD, MEASURED IN BU / ACRE, SOYBEANS - PRODUCTION, MEASURED IN BU]",NaN,NaN,NaN
10,domain_desc,object,15224,0.00,1,[TOTAL],NaN,NaN,NaN
11,domaincat_desc,object,15224,0.00,1,[NOT SPECIFIED],NaN,NaN,NaN
12,agg_level_desc,object,15224,0.00,2,"[NATIONAL, STATE]",NaN,NaN,NaN
13,state_ansi,float64,14519,4.63,48,"[1.0, 4.0, 5.0, 6.0, 8.0, 9.0, 10.0, 12.0]",1.0,29.0,5.600000e+01
14,state_fips_code,int64,15224,0.00,50,"[99, 98, 1, 4, 5, 6, 8, 9]",1.0,30.0,9.900000e+01
15,state_alpha,object,15224,0.00,50,"[US, OT, AL, AZ, AR, CA, CO, CT]",NaN,NaN,NaN
16,state_name,object,15224,0.00,50,"[US TOTAL, OTHER STATES, ALABAMA, ARIZONA, ARKANSAS, CALIFORNIA, COLORADO, CONNECTICUT]",NaN,NaN,NaN
17,asd_code,float64,0,100.00,0,[],NaN,NaN,NaN
18,asd_desc,float64,0,100.00,0,[],NaN,NaN,NaN
19,county_ansi,float64,0,100.00,0,[],NaN,NaN,NaN
20,county_code,float64,0,100.00,0,[],NaN,NaN,NaN
21,county_name,float64,0,100.00,0,[],NaN,NaN,NaN
22,region_desc,float64,0,100.00,0,[],NaN,NaN,NaN
23,zip_5,float64,0,100.00,0,[],NaN,NaN,NaN
24,watershed_code,int64,15224,0.00,1,[0],0.0,0.0,0.000000e+00
25,watershed_desc,float64,0,100.00,0,[],NaN,NaN,NaN
26,congr_district_code,float64,0,100.00,0,[],NaN,NaN,NaN
27,country_code,int64,15224,0.00,1,[9000],9000.0,9000.0,9.000000e+03
28,country_name,object,15224,0.00,1,[UNITED STATES],NaN,NaN,NaN
29,location_desc,object,15224,0.00,50,"[US TOTAL, OTHER STATES, ALABAMA, ARIZONA, ARKANSAS, CALIFORNIA, COLORADO, CONNECTICUT]",NaN,NaN,NaN
30,year,int64,15224,0.00,12,"[2026, 2025, 2024, 2023, 2022, 2021, 2020, 2019]",2015.0,2020.0,2.026000e+03
31,freq_desc,object,15224,0.00,1,[ANNUAL],NaN,NaN,NaN
32,begin_code,int64,15224,0.00,1,[0],0.0,0.0,0.000000e+00
33,end_code,int64,15224,0.00,1,[0],0.0,0.0,0.000000e+00
34,reference_period_desc,object,15224,0.00,9,"[YEAR, YEAR - MAR ACREAGE, YEAR - AUG FORECAST, YEAR - JUN ACREAGE, YEAR - SEP FORECAST, YEAR - OCT FORECAST, YEAR - AUG ACREAGE, YEAR - OCT ACREAGE]",NaN,NaN,NaN
35,week_ending,float64,0,100.00,0,[],NaN,NaN,NaN
36,load_time,object,15224,0.00,81,"[2026-03-31 12:00:00.000, 2026-01-12 12:00:00.000, 2025-08-12 12:00:00.000, 2025-06-30 12:00:00.000, 2025-03-31 12:00:00.000, 2025-09-12 12:00:00.000, 2025-09-30 12:00:00.000, 2024-08-12 12:00:00.000]",NaN,NaN,NaN
37,Value,object,15224,0.00,3971,"[95,338,000, 98,788,000, 97,254,000, 95,203,000, 95,326,000, 98,728,000, 90,909,000, 90,748,000]",NaN,NaN,NaN
38,CV (%),float64,0,100.00,0,[],NaN,NaN,NaN
39,Value_num,float64,15224,0.00,3971,"[95338000.0, 98788000.0, 97254000.0, 95203000.0, 95326000.0, 98728000.0, 90909000.0, 90748000.0]",0.0,900000.0,1.702055e+10

In [7]:
# 2. 重点分类列有哪些取值
key_cols = [
    "commodity_desc",
    "statisticcat_desc",
    "unit_desc",
    "short_desc",
    "agg_level_desc",
    "state_alpha",
    "reference_period_desc",
    "year",
]

for col in key_cols:
    print(f"\n## {col}")
    display(df[col].value_counts(dropna=False).head(30).to_frame("count"))

## commodity_desc

                count
commodity_desc
CORN             8568
SOYBEANS         6656

## statisticcat_desc

                   count
statisticcat_desc
AREA HARVESTED      4500
YIELD               3576
PRODUCTION          3576
AREA PLANTED        3572

## unit_desc

           count
unit_desc
ACRES       8072
BU / ACRE   3576
BU          3576

## short_desc

                                            count
short_desc
CORN, GRAIN - ACRES HARVESTED                2498
CORN - ACRES PLANTED                         2214
SOYBEANS - ACRES HARVESTED                   2002
CORN, GRAIN - YIELD, MEASURED IN BU / ACRE   1928
CORN, GRAIN - PRODUCTION, MEASURED IN BU     1928
SOYBEANS - YIELD, MEASURED IN BU / ACRE      1648
SOYBEANS - PRODUCTION, MEASURED IN BU        1648
SOYBEANS - ACRES PLANTED                     1358

## agg_level_desc

                count
agg_level_desc
STATE           14783
NATIONAL          441

## state_alpha

             count
state_alpha
US             441
TX             435
VA             435
MI             435
MN             435
MS             435
MO             435
NE             435
TN             435
PA             435
SD             435
NY             435
NC             435
ND             435
OH             435
OK             435
MD             435
SC             435
LA             435
AR             435
KS             435
IA             435
IN             435
IL             435
AL             435
GA             435
KY             435
DE             435
WI             435
NJ             327

## reference_period_desc

                       count
reference_period_desc
YEAR                    3425
YEAR - SEP FORECAST     2552
YEAR - AUG FORECAST     2299
YEAR - OCT FORECAST     2185
YEAR - NOV FORECAST     2118
YEAR - JUN ACREAGE      1447
YEAR - MAR ACREAGE       959
YEAR - OCT ACREAGE       160
YEAR - AUG ACREAGE        79

## year

      count
year
2024   1504
2019   1474
2021   1469
2018   1418
2023   1390
2020   1389
2022   1378
2025   1277
2017   1259
2015   1258
2016   1250
2026    158

In [8]:
# 3. 看不同指标的 Value 范围
value_summary = (
    df.groupby(["commodity_desc", "statisticcat_desc", "unit_desc"], dropna=False)
    .agg(
        rows=("Value_num", "size"),
        non_null=("Value_num", "count"),
        min_value=("Value_num", "min"),
        median_value=("Value_num", "median"),
        max_value=("Value_num", "max"),
    )
    .reset_index()
    .sort_values(["commodity_desc", "statisticcat_desc"])
)

display(value_summary)

,commodity_desc,statisticcat_desc,unit_desc,rows,non_null,min_value,median_value,max_value
0,CORN,AREA HARVESTED,ACRES,2498,2498,0.0,730000.0,9.125800e+07
1,CORN,AREA PLANTED,ACRES,2214,2214,0.0,470000.0,9.878800e+07
2,CORN,PRODUCTION,BU,1928,1928,0.0,130940000.0,1.702055e+10
3,CORN,YIELD,BU / ACRE,1928,1928,0.0,167.0,2.550000e+02
4,SOYBEANS,AREA HARVESTED,ACRES,2002,2002,0.0,1820000.0,8.954200e+07
5,SOYBEANS,AREA PLANTED,ACRES,1358,1358,0.0,1845000.0,9.095500e+07
6,SOYBEANS,PRODUCTION,BU,1648,1648,0.0,93040000.0,4.693135e+09
7,SOYBEANS,YIELD,BU / ACRE,1648,1648,0.0,47.0,6.700000e+01

In [9]:
# 4. 看 short_desc 粒度下的范围，更接近业务指标
short_desc_summary = (
    df.groupby(["short_desc", "unit_desc"], dropna=False)
    .agg(
        rows=("Value_num", "size"),
        years=("year", lambda x: f"{x.min()}-{x.max()}"),
        states=("state_alpha", "nunique"),
        min_value=("Value_num", "min"),
        median_value=("Value_num", "median"),
        max_value=("Value_num", "max"),
    )
    .reset_index()
    .sort_values("short_desc")
)

display(short_desc_summary)

,short_desc,unit_desc,rows,years,states,min_value,median_value,max_value
0,CORN - ACRES PLANTED,ACRES,2214,2015-2026,50,0.0,470000.0,9.878800e+07
1,"CORN, GRAIN - ACRES HARVESTED",ACRES,2498,2015-2025,43,0.0,730000.0,9.125800e+07
2,"CORN, GRAIN - PRODUCTION, MEASURED IN BU",BU,1928,2015-2025,43,0.0,130940000.0,1.702055e+10
3,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",BU / ACRE,1928,2015-2025,43,0.0,167.0,2.550000e+02
4,SOYBEANS - ACRES HARVESTED,ACRES,2002,2015-2025,33,0.0,1820000.0,8.954200e+07
5,SOYBEANS - ACRES PLANTED,ACRES,1358,2015-2026,33,0.0,1845000.0,9.095500e+07
6,"SOYBEANS - PRODUCTION, MEASURED IN BU",BU,1648,2015-2025,33,0.0,93040000.0,4.693135e+09
7,"SOYBEANS - YIELD, MEASURED IN BU / ACRE",BU / ACRE,1648,2015-2025,33,0.0,47.0,6.700000e+01

In [10]:
# 5. 只看你 dashboard 最常用的最终年度数据
annual_final = df[
    (df["reference_period_desc"] == "YEAR")
    & (df["agg_level_desc"].isin(["NATIONAL", "STATE"]))
].copy()

pivot = annual_final.pivot_table(
    index=["commodity_desc", "year", "state_alpha", "state_name"],
    columns="statisticcat_desc",
    values="Value_num",
    aggfunc="first",
).reset_index()

display(pivot.sort_values(by=["commodity_desc", "year", "AREA HARVESTED"], ascending=[True, True, False]))

statisticcat_desc,commodity_desc,year,state_alpha,state_name,AREA HARVESTED,AREA PLANTED,PRODUCTION,YIELD
42,CORN,2015,US,US TOTAL,80753000.0,88019000.0,1.360196e+10,168.4
9,CORN,2015,IA,IOWA,13050000.0,13500000.0,2.505600e+09,192.0
11,CORN,2015,IL,ILLINOIS,11500000.0,11700000.0,2.012500e+09,175.0
26,CORN,2015,NE,NEBRASKA,9150000.0,9400000.0,1.692750e+09,185.0
20,CORN,2015,MN,MINNESOTA,7600000.0,8100000.0,1.428800e+09,188.0
...,...,...,...,...,...,...,...,...
971,SOYBEANS,2026,TN,TENNESSEE,NaN,1550000.0,NaN,NaN
972,SOYBEANS,2026,TX,TEXAS,NaN,95000.0,NaN,NaN
973,SOYBEANS,2026,US,US TOTAL,NaN,84700000.0,NaN,NaN
974,SOYBEANS,2026,VA,VIRGINIA,NaN,570000.0,NaN,NaN
975,SOYBEANS,2026,WI,WISCONSIN,NaN,2400000.0,NaN,NaN

## crop_progress_condition_raw.csv

In [13]:
path_crop_progress = "data/raw/nass/crop_progress_condition_raw.csv"
df_crop_progress = pd.read_csv(path_crop_progress, low_memory=False)

# Basic info
print("=== CROP PROGRESS CONDITION DATA ===")
df_crop_progress.info()
print("Shape:", df_crop_progress.shape)
display(df_crop_progress.head(10))

=== CROP PROGRESS CONDITION DATA ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144848 entries, 0 to 144847
Data columns (total 39 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   source_desc            144848 non-null  object
 1   sector_desc            144848 non-null  object
 2   group_desc             144848 non-null  object
 3   commodity_desc         144848 non-null  object
 4   class_desc             144848 non-null  object
 5   prodn_practice_desc    144848 non-null  object
 6   util_practice_desc     144848 non-null  object
 7   statisticcat_desc      144848 non-null  object
 8   unit_desc              144848 non-null  object
 9   short_desc             144848 non-null  object
 10  domain_desc            144848 non-null  object
 11  domaincat_desc         144848 non-null  object
 12  agg_level_desc         144848 non-null  object
 13  state_ansi             141283 non-null  float64
 14  state_fips_code        144848 non-null  int64
 15  state_alpha            144848 non-null  object
 16  state_name             144848 non-null  object
 17  asd_code               0 non-null       float64
 18  asd_desc               0 non-null       float64
 19  county_ansi            0 non-null       float64
 20  county_code            0 non-null       float64
 21  county_name            0 non-null       float64
 22  region_desc            0 non-null       float64
 23  zip_5                  0 non-null       float64
 24  watershed_code         144848 non-null  int64
 25  watershed_desc         0 non-null       float64
 26  congr_district_code    0 non-null       float64
 27  country_code           144848 non-null  int64
 28  country_name           144848 non-null  object
 29  location_desc          144848 non-null  object
 30  year                   144848 non-null  int64
 31  freq_desc              144848 non-null  object
 32  begin_code             144848 non-null  int64
 33  end_code               144848 non-null  int64
 34  reference_period_desc  144848 non-null  object
 35  week_ending            144848 non-null  object
 36  load_time              144848 non-null  object
 37  Value                  144848 non-null  int64
 38  CV (%)                 0 non-null       float64
dtypes: float64(11), int64(7), object(21)
memory usage: 43.1+ MB
Shape: (144848, 39)

,source_desc,sector_desc,group_desc,commodity_desc,class_desc,prodn_practice_desc,util_practice_desc,statisticcat_desc,unit_desc,short_desc,domain_desc,domaincat_desc,agg_level_desc,state_ansi,state_fips_code,state_alpha,state_name,asd_code,asd_desc,county_ansi,county_code,county_name,region_desc,zip_5,watershed_code,watershed_desc,congr_district_code,country_code,country_name,location_desc,year,freq_desc,begin_code,end_code,reference_period_desc,week_ending,load_time,Value,CV (%)
0,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,WEEKLY,31,31,WEEK #31,2025-08-03,2025-08-04 16:00:00.000,6,NaN
1,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,WEEKLY,32,32,WEEK #32,2025-08-10,2025-08-11 16:00:00.000,14,NaN
2,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,WEEKLY,33,33,WEEK #33,2025-08-17,2025-08-18 16:00:00.000,27,NaN
3,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,WEEKLY,34,34,WEEK #34,2025-08-24,2025-08-25 16:00:00.000,44,NaN
4,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,WEEKLY,35,35,WEEK #35,2025-08-31,2025-09-02 16:00:00.000,58,NaN
5,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,WEEKLY,36,36,WEEK #36,2025-09-07,2025-09-08 16:00:00.000,74,NaN
6,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,WEEKLY,37,37,WEEK #37,2025-09-14,2025-09-15 16:00:00.000,85,NaN
7,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,WEEKLY,38,38,WEEK #38,2025-09-21,2025-09-22 16:00:00.000,91,NaN
8,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2025,WEEKLY,39,39,WEEK #39,2025-09-28,2025-09-29 16:00:00.000,95,NaN
9,SURVEY,CROPS,FIELD CROPS,CORN,ALL CLASSES,ALL PRODUCTION PRACTICES,ALL UTILIZATION PRACTICES,PROGRESS,PCT DENTED,"CORN - PROGRESS, MEASURED IN PCT DENTED",TOTAL,NOT SPECIFIED,NATIONAL,NaN,99,US,US TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,9000,UNITED STATES,US TOTAL,2024,WEEKLY,31,31,WEEK #31,2024-08-04,2024-08-05 16:00:00.000,7,NaN

In [14]:
# Data cleaning - convert Value column to numeric
df_crop_progress["Value_num"] = (
    df_crop_progress["Value"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace(r"[^0-9.\-]", "", regex=True)
)
df_crop_progress["Value_num"] = pd.to_numeric(df_crop_progress["Value_num"], errors="coerce")

In [15]:
# Profile each column
profile_crop = []
for col in df_crop_progress.columns:
    s = df_crop_progress[col]
    row = {
        "column": col,
        "dtype": str(s.dtype),
        "non_null": int(s.notna().sum()),
        "missing_pct": round(s.isna().mean() * 100, 2),
        "n_unique": int(s.nunique(dropna=True)),
        "sample_values": s.dropna().astype(str).unique()[:8].tolist(),
    }

    if pd.api.types.is_numeric_dtype(s):
        row.update({
            "min": s.min(),
            "median": s.median(),
            "max": s.max(),
        })
    else:
        row.update({
            "min": None,
            "median": None,
            "max": None,
        })

    profile_crop.append(row)

profile_crop_df = pd.DataFrame(profile_crop)
display(profile_crop_df)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

,column,dtype,non_null,missing_pct,n_unique,sample_values,min,median,max
0,source_desc,object,144848,0.00,1,[SURVEY],NaN,NaN,NaN
1,sector_desc,object,144848,0.00,1,[CROPS],NaN,NaN,NaN
2,group_desc,object,144848,0.00,1,[FIELD CROPS],NaN,NaN,NaN
3,commodity_desc,object,144848,0.00,2,"[CORN, SOYBEANS]",NaN,NaN,NaN
4,class_desc,object,144848,0.00,1,[ALL CLASSES],NaN,NaN,NaN
5,prodn_practice_desc,object,144848,0.00,1,[ALL PRODUCTION PRACTICES],NaN,NaN,NaN
6,util_practice_desc,object,144848,0.00,3,"[ALL UTILIZATION PRACTICES, GRAIN, SILAGE]",NaN,NaN,NaN
7,statisticcat_desc,object,144848,0.00,2,"[PROGRESS, CONDITION]",NaN,NaN,NaN
8,unit_desc,object,144848,0.00,19,"[PCT DENTED, PCT DOUGH, PCT EMERGED, PCT MATURE, PCT PLANTED, PCT SILKING, PCT HARVESTED, PCT MILK]",NaN,NaN,NaN
9,short_desc,object,144848,0.00,30,"[CORN - PROGRESS, MEASURED IN PCT DENTED, CORN - PROGRESS, MEASURED IN PCT DOUGH, CORN - PROGRESS, MEASURED IN PCT EMERGED, CORN - PROGRESS, MEASURED IN PCT MATURE, CORN - PROGRESS, MEASURED IN PCT PLANTED, CORN - PROGRESS, MEASURED IN PCT SILKING, CORN, GRAIN - PROGRESS, MEASURED IN PCT HARVESTED, CORN - PROGRESS, MEASURED IN PCT MILK]",NaN,NaN,NaN
10,domain_desc,object,144848,0.00,1,[TOTAL],NaN,NaN,NaN
11,domaincat_desc,object,144848,0.00,1,[NOT SPECIFIED],NaN,NaN,NaN
12,agg_level_desc,object,144848,0.00,2,"[NATIONAL, STATE]",NaN,NaN,NaN
13,state_ansi,float64,141283,2.46,44,"[1.0, 5.0, 8.0, 9.0, 10.0, 16.0, 17.0, 18.0]",1.0,31.0,56.0
14,state_fips_code,int64,144848,0.00,45,"[99, 1, 5, 8, 9, 10, 16, 17]",1.0,33.0,99.0
15,state_alpha,object,144848,0.00,45,"[US, AL, AR, CO, CT, DE, ID, IL]",NaN,NaN,NaN
16,state_name,object,144848,0.00,45,"[US TOTAL, ALABAMA, ARKANSAS, COLORADO, CONNECTICUT, DELAWARE, IDAHO, ILLINOIS]",NaN,NaN,NaN
17,asd_code,float64,0,100.00,0,[],NaN,NaN,NaN
18,asd_desc,float64,0,100.00,0,[],NaN,NaN,NaN
19,county_ansi,float64,0,100.00,0,[],NaN,NaN,NaN
20,county_code,float64,0,100.00,0,[],NaN,NaN,NaN
21,county_name,float64,0,100.00,0,[],NaN,NaN,NaN
22,region_desc,float64,0,100.00,0,[],NaN,NaN,NaN
23,zip_5,float64,0,100.00,0,[],NaN,NaN,NaN
24,watershed_code,int64,144848,0.00,1,[0],0.0,0.0,0.0
25,watershed_desc,float64,0,100.00,0,[],NaN,NaN,NaN
26,congr_district_code,float64,0,100.00,0,[],NaN,NaN,NaN
27,country_code,int64,144848,0.00,1,[9000],9000.0,9000.0,9000.0
28,country_name,object,144848,0.00,1,[UNITED STATES],NaN,NaN,NaN
29,location_desc,object,144848,0.00,45,"[US TOTAL, ALABAMA, ARKANSAS, COLORADO, CONNECTICUT, DELAWARE, IDAHO, ILLINOIS]",NaN,NaN,NaN
30,year,int64,144848,0.00,12,"[2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018]",2015.0,2020.0,2026.0
31,freq_desc,object,144848,0.00,1,[WEEKLY],NaN,NaN,NaN
32,begin_code,int64,144848,0.00,45,"[31, 32, 33, 34, 35, 36, 37, 38]",1.0,31.0,53.0
33,end_code,int64,144848,0.00,45,"[31, 32, 33, 34, 35, 36, 37, 38]",1.0,31.0,53.0
34,reference_period_desc,object,144848,0.00,45,"[WEEK #31, WEEK #32, WEEK #33, WEEK #34, WEEK #35, WEEK #36, WEEK #37, WEEK #38]",NaN,NaN,NaN
35,week_ending,object,144848,0.00,456,"[2025-08-03, 2025-08-10, 2025-08-17, 2025-08-24, 2025-08-31, 2025-09-07, 2025-09-14, 2025-09-21]",NaN,NaN,NaN
36,load_time,object,144848,0.00,462,"[2025-08-04 16:00:00.000, 2025-08-11 16:00:00.000, 2025-08-18 16:00:00.000, 2025-08-25 16:00:00.000, 2025-09-02 16:00:00.000, 2025-09-08 16:00:00.000, 2025-09-15 16:00:00.000, 2025-09-22 16:00:00.000]",NaN,NaN,NaN
37,Value,int64,144848,0.00,101,"[6, 14, 27, 44, 58, 74, 85, 91]",0.0,21.0,100.0
38,CV (%),float64,0,100.00,0,[],NaN,NaN,NaN
39,Value_num,int64,144848,0.00,101,"[6, 14, 27, 44, 58, 74, 85, 91]",0.0,21.0,100.0

In [18]:
# Key categorical columns analysis
key_cols_crop = [col for col in df_crop_progress.columns 
                 if df_crop_progress[col].dtype == 'object' or 
                 df_crop_progress[col].nunique() < 50]

print("\n=== KEY CATEGORICAL VALUES ===")
for col in key_cols_crop[:10]:  # Limit to first 10
    print(f"\n## {col}")
    display(df_crop_progress[col].value_counts(dropna=False).head(20).to_frame("count"))


# Value range by key dimensions
print("\n=== VALUE RANGES BY DIMENSIONS ===")
crop_progress_summary = (
    df_crop_progress.groupby(["commodity_desc", "statisticcat_desc", "unit_desc"], dropna=False)
    .agg(
        rows=("Value_num", "size"),
        non_null=("Value_num", "count"),
        min_value=("Value_num", "min"),
        median_value=("Value_num", "median"),
        max_value=("Value_num", "max"),
    )
    .reset_index()
    .sort_values(["commodity_desc", "statisticcat_desc"])
)
display(crop_progress_summary)

=== KEY CATEGORICAL VALUES ===

## source_desc

              count
source_desc
SURVEY       144848

## sector_desc

              count
sector_desc
CROPS        144848

## group_desc

              count
group_desc
FIELD CROPS  144848

## commodity_desc

                count
commodity_desc
CORN            84838
SOYBEANS        60010

## class_desc

              count
class_desc
ALL CLASSES  144848

## prodn_practice_desc

                           count
prodn_practice_desc
ALL PRODUCTION PRACTICES  144848

## util_practice_desc

                            count
util_practice_desc
ALL UTILIZATION PRACTICES  137725
GRAIN                        4722
SILAGE                       2401

## statisticcat_desc

                   count
statisticcat_desc
CONDITION          88325
PROGRESS           56523

## unit_desc

                      count
unit_desc
PCT EXCELLENT         17665
PCT VERY POOR         17665
PCT FAIR              17665
PCT GOOD              17665
PCT POOR              17665
PCT HARVESTED         10592
PCT PLANTED            9654
PCT EMERGED            8706
PCT MATURE             4345
PCT SILKING            3796
PCT BLOOMING           3665
PCT DOUGH              3616
PCT SETTING PODS       3609
PCT DENTED             3539
PCT DROPPING LEAVES    3212
PCT COLORING           1170
PCT MILK                351
PCT FULLY PODDED        238
PCT SEEDBED PREPARED     30

## short_desc

                                                   count
short_desc
CORN - CONDITION, MEASURED IN PCT VERY POOR        10457
CORN - CONDITION, MEASURED IN PCT POOR             10457
CORN - CONDITION, MEASURED IN PCT GOOD             10457
CORN - CONDITION, MEASURED IN PCT FAIR             10457
CORN - CONDITION, MEASURED IN PCT EXCELLENT        10457
SOYBEANS - CONDITION, MEASURED IN PCT VERY POOR     7208
SOYBEANS - CONDITION, MEASURED IN PCT FAIR          7208
SOYBEANS - CONDITION, MEASURED IN PCT EXCELLENT     7208
SOYBEANS - CONDITION, MEASURED IN PCT GOOD          7208
SOYBEANS - CONDITION, MEASURED IN PCT POOR          7208
CORN - PROGRESS, MEASURED IN PCT PLANTED            5388
CORN - PROGRESS, MEASURED IN PCT EMERGED            4947
CORN, GRAIN - PROGRESS, MEASURED IN PCT HARVESTED   4722
SOYBEANS - PROGRESS, MEASURED IN PCT PLANTED        4266
CORN - PROGRESS, MEASURED IN PCT SILKING            3796
CORN - PROGRESS, MEASURED IN PCT MATURE             3779
SOYBEANS - PROGRESS, MEASURED IN PCT EMERGED        3759
SOYBEANS - PROGRESS, MEASURED IN PCT BLOOMING       3665
CORN - PROGRESS, MEASURED IN PCT DOUGH              3616
SOYBEANS - PROGRESS, MEASURED IN PCT SETTING PODS   3609

=== VALUE RANGES BY DIMENSIONS ===

,commodity_desc,statisticcat_desc,unit_desc,rows,non_null,min_value,median_value,max_value
0,CORN,CONDITION,PCT EXCELLENT,10457,10457,0,12.0,100
1,CORN,CONDITION,PCT FAIR,10457,10457,0,23.0,94
2,CORN,CONDITION,PCT GOOD,10457,10457,0,54.0,100
3,CORN,CONDITION,PCT POOR,10457,10457,0,5.0,100
4,CORN,CONDITION,PCT VERY POOR,10457,10457,0,1.0,52
5,CORN,PROGRESS,PCT DENTED,3539,3539,0,64.0,100
6,CORN,PROGRESS,PCT DOUGH,3616,3616,0,63.5,100
7,CORN,PROGRESS,PCT EMERGED,4947,4947,0,60.0,100
8,CORN,PROGRESS,PCT HARVESTED,7123,7123,0,51.0,100
9,CORN,PROGRESS,PCT MATURE,3779,3779,0,61.0,100
10,CORN,PROGRESS,PCT MILK,351,351,0,66.0,100
11,CORN,PROGRESS,PCT PLANTED,5388,5388,0,56.0,100
12,CORN,PROGRESS,PCT SEEDBED PREPARED,14,14,10,85.5,100
13,CORN,PROGRESS,PCT SILKING,3796,3796,0,59.0,100
14,SOYBEANS,CONDITION,PCT EXCELLENT,7208,7208,0,10.0,52
15,SOYBEANS,CONDITION,PCT FAIR,7208,7208,0,27.0,74
16,SOYBEANS,CONDITION,PCT GOOD,7208,7208,0,53.0,100
17,SOYBEANS,CONDITION,PCT POOR,7208,7208,0,6.0,67
18,SOYBEANS,CONDITION,PCT VERY POOR,7208,7208,0,2.0,39
19,SOYBEANS,PROGRESS,PCT BLOOMING,3665,3665,0,65.0,100
20,SOYBEANS,PROGRESS,PCT COLORING,1170,1170,0,58.0,100
21,SOYBEANS,PROGRESS,PCT DROPPING LEAVES,3212,3212,0,57.0,100
22,SOYBEANS,PROGRESS,PCT EMERGED,3759,3759,0,62.0,100
23,SOYBEANS,PROGRESS,PCT FULLY PODDED,238,238,0,64.0,100
24,SOYBEANS,PROGRESS,PCT HARVESTED,3469,3469,0,52.0,100
25,SOYBEANS,PROGRESS,PCT MATURE,566,566,0,68.0,100
26,SOYBEANS,PROGRESS,PCT PLANTED,4266,4266,0,57.0,100
27,SOYBEANS,PROGRESS,PCT SEEDBED PREPARED,16,16,3,48.5,86
28,SOYBEANS,PROGRESS,PCT SETTING PODS,3609,3609,0,64.0,100